eosexe = "/afs/cern.ch/project/eos/installation/0.3.84-aquamarine/bin/eos.select"
ptype = "904"
poolsource = "root://eoscms.cern.ch//eos/cms/store/group/dpg_hcal/comm_hcal/B904/"
process_lock = "process_904.lock"
upload_lock = "upload_904.lock"
cmssw_config = "/afs/cern.ch/work/c/cmshcaldqm/HCALDQM/904/CMSSW_8_0_17_toProcess904/src/hcal_dqm_local_cfg.py"
cmssw_outputpool = "/home/HCALDQM/output"
cmssw_src_directory = "/afs/cern.ch/work/c/cmshcaldqm/HCALDQM/904/CMSSW_8_0_17_toProcess904/src"
cmssw_output_template = "DQM_V0001_R{runNumber}__{runType}__Commissioning2016__DQMIO.root"
cmsRun_cmd_template = "cmsRun {cmssw_config} inputFiles={pathToFileName} runType={runType}"

dqmgui_server_name = "cmshcaldqm-vm.cern.ch:8070/dqm/online-dev"
dqmupload_cmd_template = "visDQMUpload http://{server_name} {pathnameToFile}"

dbpathname = "/afs/cern.ch/work/c/cmshcaldqm/HCALDQM/ToolBox/904runs.db"
table_name = "Runs"
oracledbstring = "cms_hcl_test_runinfo/run2013info@cms_orcoff_prep"
